### ISSUE TITLE
Pom.xml

### ISSUE THREAD

**Issue by vnioliveira** [cesarvasconcelos/ifpb-poo#1]
Professor,a parte em que está comentada da tag build está gerando erro quando colada no intellij,retirei os comentários e o erro saiu

**Comment by vnioliveira** [comment]
e essa tag é do arquivo pom.xml

**Comment by cesarvasconcelos** [comment]
Oi, veja se quando colou no IntelliJ o código ficou dentro da tag plugins. Senão realmente não vai funcionar. Veja, comentários devem estar entre sinais de
